//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeClient.EmployeeServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Employee_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_nameField;
        
        private int DepartmentidField;
        
        private int RoleidField;
        
        private byte is_adminField;
        
        private byte on_dutyField;
        
        private System.DateTime date_joinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone_numberField;
        
        private int HolidayEntitlementField;
        
        private System.Nullable<int> ExtraDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.HolidayEntitlement[] HolidayEntitlementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.HolidayRequest[] HolidayRequestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.Department DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.Role RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Employee_id {
            get {
                return this.Employee_idField;
            }
            set {
                if ((this.Employee_idField.Equals(value) != true)) {
                    this.Employee_idField = value;
                    this.RaisePropertyChanged("Employee_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string First_name {
            get {
                return this.First_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_nameField, value) != true)) {
                    this.First_nameField = value;
                    this.RaisePropertyChanged("First_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Last_name {
            get {
                return this.Last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_nameField, value) != true)) {
                    this.Last_nameField = value;
                    this.RaisePropertyChanged("Last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Departmentid {
            get {
                return this.DepartmentidField;
            }
            set {
                if ((this.DepartmentidField.Equals(value) != true)) {
                    this.DepartmentidField = value;
                    this.RaisePropertyChanged("Departmentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Roleid {
            get {
                return this.RoleidField;
            }
            set {
                if ((this.RoleidField.Equals(value) != true)) {
                    this.RoleidField = value;
                    this.RaisePropertyChanged("Roleid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public byte is_admin {
            get {
                return this.is_adminField;
            }
            set {
                if ((this.is_adminField.Equals(value) != true)) {
                    this.is_adminField = value;
                    this.RaisePropertyChanged("is_admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public byte on_duty {
            get {
                return this.on_dutyField;
            }
            set {
                if ((this.on_dutyField.Equals(value) != true)) {
                    this.on_dutyField = value;
                    this.RaisePropertyChanged("on_duty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime date_joined {
            get {
                return this.date_joinedField;
            }
            set {
                if ((this.date_joinedField.Equals(value) != true)) {
                    this.date_joinedField = value;
                    this.RaisePropertyChanged("date_joined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Phone_number {
            get {
                return this.Phone_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.Phone_numberField, value) != true)) {
                    this.Phone_numberField = value;
                    this.RaisePropertyChanged("Phone_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int HolidayEntitlement {
            get {
                return this.HolidayEntitlementField;
            }
            set {
                if ((this.HolidayEntitlementField.Equals(value) != true)) {
                    this.HolidayEntitlementField = value;
                    this.RaisePropertyChanged("HolidayEntitlement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<int> ExtraDays {
            get {
                return this.ExtraDaysField;
            }
            set {
                if ((this.ExtraDaysField.Equals(value) != true)) {
                    this.ExtraDaysField = value;
                    this.RaisePropertyChanged("ExtraDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public EmployeeClient.EmployeeServices.HolidayEntitlement[] HolidayEntitlements {
            get {
                return this.HolidayEntitlementsField;
            }
            set {
                if ((object.ReferenceEquals(this.HolidayEntitlementsField, value) != true)) {
                    this.HolidayEntitlementsField = value;
                    this.RaisePropertyChanged("HolidayEntitlements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public EmployeeClient.EmployeeServices.HolidayRequest[] HolidayRequests {
            get {
                return this.HolidayRequestsField;
            }
            set {
                if ((object.ReferenceEquals(this.HolidayRequestsField, value) != true)) {
                    this.HolidayRequestsField = value;
                    this.RaisePropertyChanged("HolidayRequests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public EmployeeClient.EmployeeServices.Department Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public EmployeeClient.EmployeeServices.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int DepartmentidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Department_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.Employee[] EmployeesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Departmentid {
            get {
                return this.DepartmentidField;
            }
            set {
                if ((this.DepartmentidField.Equals(value) != true)) {
                    this.DepartmentidField = value;
                    this.RaisePropertyChanged("Departmentid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Department_name {
            get {
                return this.Department_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Department_nameField, value) != true)) {
                    this.Department_nameField = value;
                    this.RaisePropertyChanged("Department_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EmployeeClient.EmployeeServices.Employee[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RoleidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Role_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.Employee[] EmployeesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Roleid {
            get {
                return this.RoleidField;
            }
            set {
                if ((this.RoleidField.Equals(value) != true)) {
                    this.RoleidField = value;
                    this.RaisePropertyChanged("Roleid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Role_name {
            get {
                return this.Role_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Role_nameField, value) != true)) {
                    this.Role_nameField = value;
                    this.RaisePropertyChanged("Role_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public EmployeeClient.EmployeeServices.Employee[] Employees {
            get {
                return this.EmployeesField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeesField, value) != true)) {
                    this.EmployeesField = value;
                    this.RaisePropertyChanged("Employees");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolidayEntitlement", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HolidayEntitlement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int HolidayEntitlementIDField;
        
        private int EmployeeIDField;
        
        private int Entitlement_days_leftField;
        
        private int Extra_daysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.Employee EmployeeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int HolidayEntitlementID {
            get {
                return this.HolidayEntitlementIDField;
            }
            set {
                if ((this.HolidayEntitlementIDField.Equals(value) != true)) {
                    this.HolidayEntitlementIDField = value;
                    this.RaisePropertyChanged("HolidayEntitlementID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Entitlement_days_left {
            get {
                return this.Entitlement_days_leftField;
            }
            set {
                if ((this.Entitlement_days_leftField.Equals(value) != true)) {
                    this.Entitlement_days_leftField = value;
                    this.RaisePropertyChanged("Entitlement_days_left");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Extra_days {
            get {
                return this.Extra_daysField;
            }
            set {
                if ((this.Extra_daysField.Equals(value) != true)) {
                    this.Extra_daysField = value;
                    this.RaisePropertyChanged("Extra_days");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EmployeeClient.EmployeeServices.Employee Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolidayRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HolidayRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int HolidayRequestIDField;
        
        private int EmployeeIDField;
        
        private System.DateTime start_dateField;
        
        private System.DateTime end_dateField;
        
        private System.Nullable<byte> approvedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.HolidayReqConstraint[] HolidayReqConstraintsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.Employee EmployeeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int HolidayRequestID {
            get {
                return this.HolidayRequestIDField;
            }
            set {
                if ((this.HolidayRequestIDField.Equals(value) != true)) {
                    this.HolidayRequestIDField = value;
                    this.RaisePropertyChanged("HolidayRequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((this.EmployeeIDField.Equals(value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime start_date {
            get {
                return this.start_dateField;
            }
            set {
                if ((this.start_dateField.Equals(value) != true)) {
                    this.start_dateField = value;
                    this.RaisePropertyChanged("start_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime end_date {
            get {
                return this.end_dateField;
            }
            set {
                if ((this.end_dateField.Equals(value) != true)) {
                    this.end_dateField = value;
                    this.RaisePropertyChanged("end_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<byte> approved {
            get {
                return this.approvedField;
            }
            set {
                if ((this.approvedField.Equals(value) != true)) {
                    this.approvedField = value;
                    this.RaisePropertyChanged("approved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public EmployeeClient.EmployeeServices.HolidayReqConstraint[] HolidayReqConstraints {
            get {
                return this.HolidayReqConstraintsField;
            }
            set {
                if ((object.ReferenceEquals(this.HolidayReqConstraintsField, value) != true)) {
                    this.HolidayReqConstraintsField = value;
                    this.RaisePropertyChanged("HolidayReqConstraints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public EmployeeClient.EmployeeServices.Employee Employee {
            get {
                return this.EmployeeField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeField, value) != true)) {
                    this.EmployeeField = value;
                    this.RaisePropertyChanged("Employee");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolidayReqConstraint", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HolidayReqConstraint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int HolidayReqConstraintsIDField;
        
        private int HolidayRequestIDField;
        
        private int ConstraintIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.HolidayRequest HolidayRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.Constraint ConstraintField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int HolidayReqConstraintsID {
            get {
                return this.HolidayReqConstraintsIDField;
            }
            set {
                if ((this.HolidayReqConstraintsIDField.Equals(value) != true)) {
                    this.HolidayReqConstraintsIDField = value;
                    this.RaisePropertyChanged("HolidayReqConstraintsID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int HolidayRequestID {
            get {
                return this.HolidayRequestIDField;
            }
            set {
                if ((this.HolidayRequestIDField.Equals(value) != true)) {
                    this.HolidayRequestIDField = value;
                    this.RaisePropertyChanged("HolidayRequestID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ConstraintID {
            get {
                return this.ConstraintIDField;
            }
            set {
                if ((this.ConstraintIDField.Equals(value) != true)) {
                    this.ConstraintIDField = value;
                    this.RaisePropertyChanged("ConstraintID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public EmployeeClient.EmployeeServices.HolidayRequest HolidayRequest {
            get {
                return this.HolidayRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.HolidayRequestField, value) != true)) {
                    this.HolidayRequestField = value;
                    this.RaisePropertyChanged("HolidayRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public EmployeeClient.EmployeeServices.Constraint Constraint {
            get {
                return this.ConstraintField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstraintField, value) != true)) {
                    this.ConstraintField = value;
                    this.RaisePropertyChanged("Constraint");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Constraint", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Constraint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ConstraintIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EmployeeClient.EmployeeServices.HolidayReqConstraint[] HolidayReqConstraintsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ConstraintID {
            get {
                return this.ConstraintIDField;
            }
            set {
                if ((this.ConstraintIDField.Equals(value) != true)) {
                    this.ConstraintIDField = value;
                    this.RaisePropertyChanged("ConstraintID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EmployeeClient.EmployeeServices.HolidayReqConstraint[] HolidayReqConstraints {
            get {
                return this.HolidayReqConstraintsField;
            }
            set {
                if ((object.ReferenceEquals(this.HolidayReqConstraintsField, value) != true)) {
                    this.HolidayReqConstraintsField = value;
                    this.RaisePropertyChanged("HolidayReqConstraints");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeServices.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        EmployeeClient.EmployeeServices.HelloWorldResponse HelloWorld(EmployeeClient.EmployeeServices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeClient.EmployeeServices.HelloWorldResponse> HelloWorldAsync(EmployeeClient.EmployeeServices.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        EmployeeClient.EmployeeServices.LoginResponse Login(EmployeeClient.EmployeeServices.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeClient.EmployeeServices.LoginResponse> LoginAsync(EmployeeClient.EmployeeServices.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeClient.EmployeeServices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(EmployeeClient.EmployeeServices.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeClient.EmployeeServices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(EmployeeClient.EmployeeServices.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeClient.EmployeeServices.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(EmployeeClient.EmployeeServices.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeClient.EmployeeServices.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(EmployeeClient.EmployeeServices.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EmployeeClient.EmployeeServices.Employee[] LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(EmployeeClient.EmployeeServices.Employee[] LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : EmployeeClient.EmployeeServices.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<EmployeeClient.EmployeeServices.WebServiceSoap>, EmployeeClient.EmployeeServices.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeClient.EmployeeServices.HelloWorldResponse EmployeeClient.EmployeeServices.WebServiceSoap.HelloWorld(EmployeeClient.EmployeeServices.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            EmployeeClient.EmployeeServices.HelloWorldRequest inValue = new EmployeeClient.EmployeeServices.HelloWorldRequest();
            inValue.Body = new EmployeeClient.EmployeeServices.HelloWorldRequestBody();
            EmployeeClient.EmployeeServices.HelloWorldResponse retVal = ((EmployeeClient.EmployeeServices.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeClient.EmployeeServices.HelloWorldResponse> EmployeeClient.EmployeeServices.WebServiceSoap.HelloWorldAsync(EmployeeClient.EmployeeServices.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeClient.EmployeeServices.HelloWorldResponse> HelloWorldAsync() {
            EmployeeClient.EmployeeServices.HelloWorldRequest inValue = new EmployeeClient.EmployeeServices.HelloWorldRequest();
            inValue.Body = new EmployeeClient.EmployeeServices.HelloWorldRequestBody();
            return ((EmployeeClient.EmployeeServices.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeClient.EmployeeServices.LoginResponse EmployeeClient.EmployeeServices.WebServiceSoap.Login(EmployeeClient.EmployeeServices.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public EmployeeClient.EmployeeServices.Employee[] Login(string username, string password) {
            EmployeeClient.EmployeeServices.LoginRequest inValue = new EmployeeClient.EmployeeServices.LoginRequest();
            inValue.Body = new EmployeeClient.EmployeeServices.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            EmployeeClient.EmployeeServices.LoginResponse retVal = ((EmployeeClient.EmployeeServices.WebServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeClient.EmployeeServices.LoginResponse> EmployeeClient.EmployeeServices.WebServiceSoap.LoginAsync(EmployeeClient.EmployeeServices.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeClient.EmployeeServices.LoginResponse> LoginAsync(string username, string password) {
            EmployeeClient.EmployeeServices.LoginRequest inValue = new EmployeeClient.EmployeeServices.LoginRequest();
            inValue.Body = new EmployeeClient.EmployeeServices.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((EmployeeClient.EmployeeServices.WebServiceSoap)(this)).LoginAsync(inValue);
        }

        internal bool Love(string a)
        {
            throw new NotImplementedException();
        }
    }
}
